[[constraint]]
  name = "github.com/tidwall/gjson"
  version = "1.0.1"

[[constraint]]
  name = "github.com/docopt/docopt-go"
  version = "0.6.2"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "0.0.3"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"
