version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/jl
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: sudo apt-get update && sudo apt-get install -y python3 python3-pip
      - run: pip3 install --user cram
      - run: echo 'export PATH="${PATH}:${HOME}/.local/bin"' >> $BASH_ENV
      - run: ./script/bootstrap
      - run: ./script/test
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
